config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "food#index"
  resources :food, only: [:index, :new, :create, :destroy]
  resources :recipe, only: [:index, :show, :new, :create, :destroy, :update] do
      resources :recipe_food, only: [:new, :create, :destroy, :update, :edit]
  end 
  resources :public_recipe, only: [:index]
  resources :general_shopping_list, only: [:index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :read, Recipe, user_id: user.id
    can :manage, Recipe, user_id: user.id unless user.nil?
    can :manage, Food, user_id: user.id unless user.nil?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods, dependent: :destroy
  has_many :recipes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/food_controller.rb
class FoodController < ApplicationController
  def index
    @foods = current_user.foods
  end

  def new
    @food = Food.new
    @user = current_user
  end

  def create
    @user = current_user
    @food = @user.foods.new(food_params)
    redirect_to food_index_path(user_id: @user.id) if @food.save
  end

  def destroy
    @food = Food.find(params[:id]).destroy
    redirect_to food_index_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def Index
    @foods = current_user.foods
  end
end

app/controllers/general_shopping_list_controller.rb
class GeneralShoppingListController < ApplicationController
  before_action :set_recipe, only: [:index]
  before_action :set_user, only: [:index]

  def index
    @recipe_foods = @recipe.recipe_foods.includes(:food).order(:id)

    @missing_foods = @recipe_foods.select { |recipe_food| recipe_food.quantity.to_i > recipe_food.food.quantity }
    @missing_foods = @missing_foods.map do |recipe_food|
      {
        name: recipe_food.food.name,
        unit: recipe_food.food.measurement_unit,
        quantity: recipe_food.quantity.to_i - recipe_food.food.quantity,
        price: recipe_food.food.price * (recipe_food.quantity.to_i - recipe_food.food.quantity)
      }
    end

    @total_price = @missing_foods.map { |recipe_food| recipe_food[:price] }.sum
  end

  private

  def set_user
    @user = current_user
  end

  def set_recipe
    @recipe = set_user.recipes.find(params[:recipe_id])
  end
end

app/controllers/public_recipe_controller.rb
class PublicRecipeController < ApplicationController
  def index
    @recipes = Recipe.where(public: true).order(id: :desc)
  end
end

app/controllers/recipe_controller.rb
class RecipeController < ApplicationController
  load_and_authorize_resource

  def index
    @recipes = current_user.recipes
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = @recipe.recipe_foods.includes(:food)
    @foods = current_user.foods
  end

  def new
    @recipe = Recipe.new
    @user = current_user
  end

  def create
    @user = current_user
    @recipe = @user.recipes.new(recipe_params)
    redirect_to recipe_index_path if @recipe.save
  end

  def destroy
    @recipe = Recipe.find(params[:id]).destroy
    # redirect_to public_recipe_index_path
    # if current_page?(controller: 'recipe', action: 'checkout')
    # redirect_to public_recipe_index_path
    # else
    redirect_to recipe_index_path
    # end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.public = !@recipe.public
    @recipe.save
    redirect_to public_recipe_index_path
  end

  def toggle
    @recipe = Recipe.find(params[:id])
    @recipe.public = !@recipe.public
    redirect_to user_recipe_path(current_user, @recipe)
  end

  def public_recipe
    @recipies = Recipe.where(public: true).includes(:user)
    @total_price = 0
    @recipies.each do |recipe|
      recipe.recipe_foods.each do |recipe_food|
        @total_price += recipe_food.food.price
      end
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/recipe_food_controller.rb
class RecipeFoodController < ApplicationController
  before_action :set_recipe_food, only: %i[edit update destroy]
  before_action :set_recipe, only: %i[show edit new create destroy]
  before_action :set_food, only: %i[create update]
  before_action :set_user, only: %i[index show new edit create]

  def new
    @recipe_food = RecipeFood.new
  end

  def edit
    @recipe_food
  end

  def create
    @recipe_food = RecipeFood.new(recipe: @recipe, food: @food, quantity: recipe_food_params[:quantity])

    if @recipe_food.save
      flash[:success] = 'Recipe food was successfully created.'
      redirect_to recipe_index_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @recipe_food.update(food: @food, quantity: recipe_food_params[:quantity])
      flash[:success] = 'Recipe food was successfully updated.'
      redirect_to recipe_url(@recipe)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @recipe_food.destroy
      flash[:success] = 'Recipe food was successfully removed.'
    else
      flash.now[:error] = 'Error: Recipe food could not be removed'
    end
    redirect_to recipe_url(@recipe)
  end

  private

  def set_user
    @user = current_user
  end

  def set_recipe
    @recipe = set_user.recipes.find(params[:recipe_id])
  end

  def set_recipe_food
    @recipe_food = set_recipe.recipe_foods.find(params[:id])
  end

  def set_food
    @food = set_user.foods.find(recipe_food_params[:food_id])
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_helper.rb
module FoodHelper
end

app/helpers/public_recipe_helper.rb
module PublicRecipeHelper
end

app/helpers/recipe_food_helper.rb
module RecipeFoodHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/food/index.html.erb
<div class="foodList" >
<%= link_to "New Food", new_food_path, class: "addFoodBtn" %>

<table class=table>
<tr class="tableHeading" >
  <th>Food</th>
  <th>Mesurment Unit</th>
  <th>Unit Price</th>
  <th>Action</th>
</tr>
<% @foods.each do |food| %>
<tr>
  <td><%= food.name %></td>
  <td><%= food.measurement_unit %></td>
  <td><%= food.price %></td>
  <td>
  <%= button_to 'DELETE', food_path(id: food.id), method: :delete, class: "foodDeleteBtn" %>
  </td>
</tr>
<% end %>
</table>

</div>

app/views/food/new.html.erb
<div class="addFoodContainer"> 
<h1 class="addFoodHeader"> Create Food </h1>
<div class="addFoodForm">
<%= form_with model: @food, url: food_index_path, local: true do |f| %>
    <p>
    <%= f.label :name, class: "foodFormLabel" %> <br>
    <%= f.text_field :name, placeholder: 'Name', class: "foodFormField" %>
    </p>
    <p>
    <%= f.label :measurement_unit, class: "foodFormLabel"  %> <br>
    <%= f.text_field :measurement_unit, placeholder: 'Measurement Unit', class: "foodFormField" %>
    </p>
    <p>
    <%= f.label :price, class: "foodFormLabel" %> <br>
    <%= f.text_field :price, placeholder: 'Price', class: "foodFormField" %>
    </p>
    <p>
     <%= f.label :quantity, class: "foodFormLabel" %> <br>
    <%= f.text_field :quantity, placeholder: 'Quantity', class: "foodFormField" %>
    </p>
    <%= f.submit 'Submit', class: "foodFormSubmit" %>
<% end %>
</div>
</div>

app/views/foods/index.html.erb
<div class="foodsMainContainer">
  <div class="foodsHeadings">
    <p>Food</p>
    <p>Mesurment Unit</p>
    <p>Unit Price</p>
    <p>Action</p>
  </div>
  <ul class="foodsList">
    <%@foods.each do |food|%>
      <li class="foodsListItem">
        <div class="itemOne">
          <p>
            <%= food.name%>
          </p>
        </div>
        <div class="itemTwo">
          <p>
            <%= food.measurement_unit%>
          </p>
        </div>
        <div class="itemThree">
          <p>
            <%= food.quantity%>
          </p>
        </div>
        <div class="itemFour">
          <button>
            Delete
          </button>
        </div>
      </li>
    <%end%>
  </ul>
</div>

app/views/general_shopping_list/_food.html.erb
<tr >
  <td >
    <%= food[:name] %>
  </td>
  <td >
    <%= food[:quantity] %> <%= food[:unit] %>
  </td>
  <td >
    $<%= food[:price] %>
  </td>
</tr>

app/views/general_shopping_list/index.html.erb
<div class="generalShoppingContainer">
<h1 class="generalShoppingTitle">General Shopping List for <%= @recipe.name %> </h1>
<% if @missing_foods.count == 0 %>
  <p class="text"> All food is available for this recipe </p>
<% else %>
  <div class="missingFoodInfo">
    <p class="text">Amount of food to buy: <%= @missing_foods.count %></p>
    <p class="text">Total value of foods needed: $<%= @total_price %> </p>
  </div>
  <div class="generalShoppingListTableContainer">
    <table >
      <thead >
        <tr >
          <th >
            Food
          </th>
          <th >
            Quantity
          </th>
          <th >
            Price
          </th>
        </tr>
      </thead>
      <tbody>
        <%@missing_foods.each do |food| %>
          <%= render "food", food: food %>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>
</div>

app/views/layouts/_navbar.html.erb
<header>
  <div class=container>
    <nav class="navBar">
      <div class="navWellcome">
        <h1>Welcome to Recipe App</h1>
        <p class="wellcomeMsg">
          you are logged in as: <%= current_user.email %>
        </p>
      </div>
      <ul class="navLinks">
        <li><%= link_to 'FOODS', food_index_path, class: "navLink" %></li>
        <li><%= link_to 'RECIPES', recipe_index_path, class: "navLink" %></li>
        <li><%= link_to 'PUBLIC RECIPES', public_recipe_index_path, class: "navLink" %></li>
        <% if user_signed_in? %>
          <li><%= button_to 'SIGN OUT', destroy_user_session_path, method: :delete, data: {turbo: false}, class: "signOutBtn" %></li>
        <% else %>
          <li><%= link_to 'SIGN IN' %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <% if user_signed_in? %>
      <%= render "layouts/navbar" %>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/public_recipe/index.html.erb
<%if @recipes.length == 0%>
  <h1 class="text"> There are no public recipes </h1>
<%else%>
  <% @recipes.each_with_index do |recipe, idx| %>
      <div class=index-container>
        <div class=recipe-card>
          <div class=left-box>
            <h2><%= recipe.name %></h2>
          </div>
          <div class=right-box>
            <%= recipe.description %>
            <% if can? :manage, recipe %>
            <%= button_to 'REMOVE', recipe_path(id: recipe.id), method: :delete, class: "deleteRecipeLink" %>
          <% end %>
           <%= link_to "Details", recipe_path(recipe.id),  class: "showRecipeLink" %>
          </div>
        </div>
      </div>
    <%end%>
<%end%>

app/views/recipe/index.html.erb
<p class="helloMessage" >
<%= "Hi #{current_user.name}, would you like to add a recipe?" %><br>
</p>
<%= link_to 'Add Recipe', new_recipe_path, class: "addFoodBtn" %>

<% @recipes.each_with_index do |recipe, idx| %>
    <div class=index-container>
      <div class=recipe-card>
        <div class=left-box>
        <%= link_to recipe_path(recipe.id) do %>
          <p><%= "Show RECIPE #{idx+1}" %></p>
          <% end %>
          <h2><%= recipe.name %></h2>
          <% if can? :manage, recipe %>
            <%= button_to 'REMOVE', recipe_path(id: recipe.id), method: :delete %>
          <% end %>
        </div>
        <div class=right-box>
          <%= recipe.description %>
        </div>
      </div>
    </div>
<%end%>

app/views/recipe/new.html.erb
<div class="newRecipeContainer">
<h1 class="newRecipeTitle">
Create Recipe
</h1>

<%= form_with model: @recipe, url: recipe_index_path, local: true do |f| %>
    <p>
    <%= f.label :name, class: "foodFormLabel" %> <br>
    <%= f.text_field :name, placeholder: 'Name', class: "foodFormField wxl" %>
    </p>
    <p>
    <%= f.label :preparation_time, class: "foodFormLabel" %> <br>
    <%= f.text_field :preparation_time, placeholder: 'Preparation Time - Enter time in minutes', class: "foodFormField wxl" %>
    </p>
    <p>
    <%= f.label :cooking_time, class: "foodFormLabel" %> <br>
    <%= f.text_field :cooking_time, placeholder: 'Cooking Time - Enter time in minutes', class: "foodFormField wxl" %>
    </p>
    <p>
    <%= f.label :description, class: "foodFormLabel" %> <br>
    <%= f.text_field :description, placeholder: 'Description', class: "foodFormField wxl" %>
    </p>
    <%= f.submit 'Submit', class: "foodFormSubmit" %>

<% end %>
</div>

app/views/recipe/public_recipe.html.erb
<div class="publicListContainer">
  <h1 class="publicRecipeTitle">
    Public Recipies
  </h1>
  <div class="publicRecipesList">
  <%if @recipies.length == 0%>
      <h1 class="text"> There are no public recipes </h1>
  <%else%>
    <% @recipies.each do |recipe|%>
    <%= link_to recipe_path(recipe.id) do %>
          <p><%= "Show RECIPE #{idx+1}" %></p>
          <% end %>
        <div class="recipeCard">
          <div class="recipeCardLeft">
            <p class="recipeName">
              <%= recipe.name %>
            </p>
            <p class="recipeAuthor">
              <%= "By: #{recipe.user.name}" %>
            </p>
          </div>
          <div class="recipeCardRight">
            <p class="totalFoodItems"> Total food Items: <%= recipe.recipe_foods.all.length %> </p>
            <p class="totolPrice">Total Price: $ <%= @total_price%> </p>
          </div>
          <div>
        <% end %>
        <% end %>
      </div>
    </div>

app/views/recipe/show.html.erb
<div>
  <div class=something>
    <h2 class="recipeShowName"><%= @recipe.name %></h2>
    <%= form_with model: @recipe, url: recipe_path(user_id: current_user.id, id: @recipe.id), local: true, class: "toggleForm" do |f| %>
      <% if @recipe.public %>
        <%= f.submit 'Make it Private', class: "toggleButtonOn" %>
      <%else%>
        <%= f.submit 'Make it Public', class: "toggleButtonOff" %>
      <% end %>
    <% end %>
  </div>
  <p class="text">
    Preparation time: <%= @recipe.preparation_time/60.0 %> hrs <br>
  </p>
  <p class="text">
    Cooking time: <%= @recipe.cooking_time/60.0 %> hrs <br>
  </p>
  <p class="text">
    <%= @recipe.description %>
  </p>
</div>
<div class=bar-hor>
  <%= link_to 'General Shoping List', general_shopping_list_index_path(recipe_id: @recipe.id), class: "addIngredientLink" %>
  <%= link_to 'Add ingredient', new_recipe_recipe_food_path(@recipe), class: "addIngredientLink" %>
</div>
<hr>
<table class=table>
  <tr>
    <th>Food</th>
    <th>Quantity</th>
    <th>Value</th>
    <th>Actions</th>
  </tr>
  <% @recipe_foods.each do |recipe_food| %>
    <tr>
      <td><%= recipe_food.food.name %></td>
      <td>
        <%= recipe_food.quantity.to_s %>
        <%= recipe_food.food.measurement_unit%>
      </td>
      <td>
        $
        <%= recipe_food.food.price.to_i * recipe_food.quantity.to_i %>
      </td>
      <td>
        <%= link_to 'Modify', edit_recipe_recipe_food_path(recipe_id: @recipe.id, id: recipe_food.id), class: "foodDeleteBtn" %>
        <%= button_to 'Remove',recipe_recipe_food_path(recipe_id: @recipe.id, id: recipe_food.id), method: :delete, class: "foodDeleteBtn" %>
      </td>
    </tr>
  <% end %>
</table>

app/views/recipe_food/_form.html.erb
<%= form_with model: @recipe_food, url: recipe_recipe_food_index_path do |form| %>
  <% if @recipe_food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@recipe_food.errors.count, "error") %> prohibited this recipe_food from being saved:</h2>

      <ul>
        <% @recipe_food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :quantity, class: "foodFormLabel" %> <br>
    <%= form.number_field :quantity %>
  </p>

  <p>
    <%= form.label :food_id, class: "foodFormLabel" %> <br>
    <%= collection_select(:recipe_food, :food_id, @user.foods.order(name: :asc), :id, :name) %>
  </p>
  
  <p>
    <%= form.submit 'Submit', class: "foodFormSubmit" %>
  </p>
<% end %>

app/views/recipe_food/_update.html.erb
<%= form_with model: @recipe_food, url: recipe_recipe_food_path do |form| %>
  <% if @recipe_food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@recipe_food.errors.count, "error") %> prohibited this recipe_food from being saved:</h2>

      <ul>
        <% @recipe_food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :quantity, class: "foodFormLabel" %> <br>
    <%= form.number_field :quantity %>
  </p>

  <p>
    <%= form.label :food_id, class: "foodFormLabel"%> <br>
    <%= collection_select(:recipe_food, :food_id, @user.foods.order(name: :asc), :id, :name) %>
  </p>

  <div>
    <%= form.submit 'Update', class: "foodFormSubmit" %>
  </div>
<% end %>

app/views/recipe_food/edit.html.erb
<div class="recipeFoodEditContainer">
<h1 class="recipeFoodEdit">Edit Recipe Food</h1>
<%= render "update", recipe_food: @recipe_food %>
<br>
<div>
  <%= link_to "Back to recipe foods", recipe_path(@recipe)%>
</div>

</div>

app/views/recipe_food/new.html.erb
<div class="newRecipeFood">
<h1 class="newRecipeFoodTitle">Add a new food to your recipe</h1>

<%= render "form", recipe_food: @recipe_food %>
</div>

app/views/user/index.html.erb
<%= image_tag 'bg.jpg', class: "firstPage" %>